// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_scalar_mul
Rcpp::NumericVector fast_scalar_mul(double s, Rcpp::NumericVector v);
RcppExport SEXP _DefDiff_fast_scalar_mul(SEXP sSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_scalar_mul(s, v));
    return rcpp_result_gen;
END_RCPP
}
// fast_sum_sq
double fast_sum_sq(Rcpp::NumericVector v);
RcppExport SEXP _DefDiff_fast_sum_sq(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_sum_sq(v));
    return rcpp_result_gen;
END_RCPP
}
// fast_sum_pow
double fast_sum_pow(Rcpp::NumericVector v, int k);
RcppExport SEXP _DefDiff_fast_sum_pow(SEXP vSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_sum_pow(v, k));
    return rcpp_result_gen;
END_RCPP
}
// fast_vv_cos
Rcpp::NumericVector fast_vv_cos(Rcpp::NumericVector v);
RcppExport SEXP _DefDiff_fast_vv_cos(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_vv_cos(v));
    return rcpp_result_gen;
END_RCPP
}
// fast_vv_sin
Rcpp::NumericVector fast_vv_sin(Rcpp::NumericVector v);
RcppExport SEXP _DefDiff_fast_vv_sin(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_vv_sin(v));
    return rcpp_result_gen;
END_RCPP
}
// fast_vv_exp
Rcpp::NumericVector fast_vv_exp(Rcpp::NumericVector v);
RcppExport SEXP _DefDiff_fast_vv_exp(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_vv_exp(v));
    return rcpp_result_gen;
END_RCPP
}
// fast_vv_log
Rcpp::NumericVector fast_vv_log(Rcpp::NumericVector v);
RcppExport SEXP _DefDiff_fast_vv_log(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_vv_log(v));
    return rcpp_result_gen;
END_RCPP
}
// fast_vv_tanh
Rcpp::NumericVector fast_vv_tanh(Rcpp::NumericVector v);
RcppExport SEXP _DefDiff_fast_vv_tanh(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_vv_tanh(v));
    return rcpp_result_gen;
END_RCPP
}
// fast_vv_sqrt
Rcpp::NumericVector fast_vv_sqrt(Rcpp::NumericVector v);
RcppExport SEXP _DefDiff_fast_vv_sqrt(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_vv_sqrt(v));
    return rcpp_result_gen;
END_RCPP
}
// fast_vec_add
Rcpp::NumericVector fast_vec_add(Rcpp::NumericVector v, Rcpp::NumericVector w);
RcppExport SEXP _DefDiff_fast_vec_add(SEXP vSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_vec_add(v, w));
    return rcpp_result_gen;
END_RCPP
}
// fast_vec_sub
Rcpp::NumericVector fast_vec_sub(Rcpp::NumericVector v, Rcpp::NumericVector w);
RcppExport SEXP _DefDiff_fast_vec_sub(SEXP vSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_vec_sub(v, w));
    return rcpp_result_gen;
END_RCPP
}
// fast_vec_smadd
Rcpp::NumericVector fast_vec_smadd(double s, Rcpp::NumericVector v, Rcpp::NumericVector w);
RcppExport SEXP _DefDiff_fast_vec_smadd(SEXP sSEXP, SEXP vSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_vec_smadd(s, v, w));
    return rcpp_result_gen;
END_RCPP
}
// fast_scalar_div
Rcpp::NumericVector fast_scalar_div(double s, Rcpp::NumericVector v);
RcppExport SEXP _DefDiff_fast_scalar_div(SEXP sSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_scalar_div(s, v));
    return rcpp_result_gen;
END_RCPP
}
// fast_vec_mul
Rcpp::NumericVector fast_vec_mul(Rcpp::NumericVector v, Rcpp::NumericVector w);
RcppExport SEXP _DefDiff_fast_vec_mul(SEXP vSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_vec_mul(v, w));
    return rcpp_result_gen;
END_RCPP
}
// fast_vec_div
Rcpp::NumericVector fast_vec_div(Rcpp::NumericVector numerator, Rcpp::NumericVector denominator);
RcppExport SEXP _DefDiff_fast_vec_div(SEXP numeratorSEXP, SEXP denominatorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type numerator(numeratorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type denominator(denominatorSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_vec_div(numerator, denominator));
    return rcpp_result_gen;
END_RCPP
}
// metal_scalar_mul_init
bool metal_scalar_mul_init(std::string metallib_path);
RcppExport SEXP _DefDiff_metal_scalar_mul_init(SEXP metallib_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type metallib_path(metallib_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_scalar_mul_init(metallib_path));
    return rcpp_result_gen;
END_RCPP
}
// metal_scalar_mul
Rcpp::NumericVector metal_scalar_mul(double s, Rcpp::NumericVector v);
RcppExport SEXP _DefDiff_metal_scalar_mul(SEXP sSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_scalar_mul(s, v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DefDiff_fast_scalar_mul", (DL_FUNC) &_DefDiff_fast_scalar_mul, 2},
    {"_DefDiff_fast_sum_sq", (DL_FUNC) &_DefDiff_fast_sum_sq, 1},
    {"_DefDiff_fast_sum_pow", (DL_FUNC) &_DefDiff_fast_sum_pow, 2},
    {"_DefDiff_fast_vv_cos", (DL_FUNC) &_DefDiff_fast_vv_cos, 1},
    {"_DefDiff_fast_vv_sin", (DL_FUNC) &_DefDiff_fast_vv_sin, 1},
    {"_DefDiff_fast_vv_exp", (DL_FUNC) &_DefDiff_fast_vv_exp, 1},
    {"_DefDiff_fast_vv_log", (DL_FUNC) &_DefDiff_fast_vv_log, 1},
    {"_DefDiff_fast_vv_tanh", (DL_FUNC) &_DefDiff_fast_vv_tanh, 1},
    {"_DefDiff_fast_vv_sqrt", (DL_FUNC) &_DefDiff_fast_vv_sqrt, 1},
    {"_DefDiff_fast_vec_add", (DL_FUNC) &_DefDiff_fast_vec_add, 2},
    {"_DefDiff_fast_vec_sub", (DL_FUNC) &_DefDiff_fast_vec_sub, 2},
    {"_DefDiff_fast_vec_smadd", (DL_FUNC) &_DefDiff_fast_vec_smadd, 3},
    {"_DefDiff_fast_scalar_div", (DL_FUNC) &_DefDiff_fast_scalar_div, 2},
    {"_DefDiff_fast_vec_mul", (DL_FUNC) &_DefDiff_fast_vec_mul, 2},
    {"_DefDiff_fast_vec_div", (DL_FUNC) &_DefDiff_fast_vec_div, 2},
    {"_DefDiff_metal_scalar_mul_init", (DL_FUNC) &_DefDiff_metal_scalar_mul_init, 1},
    {"_DefDiff_metal_scalar_mul", (DL_FUNC) &_DefDiff_metal_scalar_mul, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DefDiff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
