# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast scalar-vector multiplication via Apple Accelerate vDSP
#'
#' Elementwise product of scalar `s` and numeric vector `v`, computed
#' through `vDSP_vsmulD` from Apple Accelerate framework (hand-tuned NEON
#' SIMD). On non-macOS platforms an error is raised. Used internally by
#' \code{grad.function} when the symbolic gradient AST matches the pattern
#' `<numeric_literal_scalar> * <variable_symbol>`.
#'
#' @param s Single finite numeric scalar.
#' @param v Numeric vector (any length, including zero).
#' @return Numeric vector of the same length as `v`, with each element equal
#'   to `s * v[i]` within `4 * .Machine$double.eps` of the R-native product.
#' @export
fast_scalar_mul <- function(s, v) {
    .Call(`_DefDiff_fast_scalar_mul`, s, v)
}

#' Fast sum-of-squares via Apple Accelerate vDSP
#'
#' Computes sum(v^2) in single pass without intermediate v^2 allocation
#' via vDSP_svesqD. Used internally by grad.function when the outer scalar
#' factor of a composite gradient contains sum(v^2).
#'
#' @param v Numeric vector.
#' @return Scalar double equal to sum(v^2).
#' @export
fast_sum_sq <- function(v) {
    .Call(`_DefDiff_fast_sum_sq`, v)
}

#' Fast sum-of-powers via Apple Accelerate vForce + vDSP
#'
#' Computes \code{sum(v^k)} for an integer power \code{k >= 2} in two passes:
#' \code{vvpow} forms the elementwise power into a scratch buffer, then
#' \code{vDSP_sveD} sums it. Generalizes \code{fast_sum_sq} (the k = 2 special
#' case) to arbitrary integer powers; the gradient side (k * v^(k-1)) is
#' handled separately by the scalar-power dispatcher. SIMD accumulation order
#' differs from R's stock \code{sum}, so the result matches to within ~1e-10
#' relative. On non-macOS platforms an error is raised.
#'
#' @param v Numeric vector.
#' @param k Integer power (>= 2).
#' @return Scalar double equal to sum(v^k).
#' @export
fast_sum_pow <- function(v, k) {
    .Call(`_DefDiff_fast_sum_pow`, v, k)
}

#' vForce cosine (Tier 2c)
#' @param v Numeric vector
#' @return Numeric vector with cos(v) elementwise via Apple Accelerate vvcos
#' @export
fast_vv_cos <- function(v) {
    .Call(`_DefDiff_fast_vv_cos`, v)
}

#' vForce sine (Tier 2c)
#' @param v Numeric vector
#' @return Numeric vector with sin(v) elementwise via Apple Accelerate vvsin
#' @export
fast_vv_sin <- function(v) {
    .Call(`_DefDiff_fast_vv_sin`, v)
}

#' vForce exponential (Tier 2c)
#' @param v Numeric vector
#' @return Numeric vector with exp(v) elementwise via Apple Accelerate vvexp
#' @export
fast_vv_exp <- function(v) {
    .Call(`_DefDiff_fast_vv_exp`, v)
}

#' vForce logarithm (Tier 2c)
#' @param v Numeric vector
#' @return Numeric vector with log(v) elementwise via Apple Accelerate vvlog
#' @export
fast_vv_log <- function(v) {
    .Call(`_DefDiff_fast_vv_log`, v)
}

#' vForce hyperbolic tangent (Tier 2c)
#' @param v Numeric vector
#' @return Numeric vector with tanh(v) elementwise via Apple Accelerate vvtanh
#' @export
fast_vv_tanh <- function(v) {
    .Call(`_DefDiff_fast_vv_tanh`, v)
}

#' vForce square root (Tier 2c)
#' @param v Numeric vector
#' @return Numeric vector with sqrt(v) elementwise via Apple Accelerate vvsqrt
#' @export
fast_vv_sqrt <- function(v) {
    .Call(`_DefDiff_fast_vv_sqrt`, v)
}

#' Fast vector-vector add via Apple Accelerate vDSP (Tier 2b)
#' @param v Numeric vector
#' @param w Numeric vector of same length
#' @return Numeric vector v + w (elementwise)
#' @export
fast_vec_add <- function(v, w) {
    .Call(`_DefDiff_fast_vec_add`, v, w)
}

#' Fast vector-vector subtract via Apple Accelerate vDSP (Tier 2b)
#' @param v Numeric vector (minuend)
#' @param w Numeric vector of same length (subtrahend)
#' @return Numeric vector v - w (elementwise)
#' @export
fast_vec_sub <- function(v, w) {
    .Call(`_DefDiff_fast_vec_sub`, v, w)
}

#' Fast scalar-multiply-add via Apple Accelerate vDSP (Tier 2b)
#' @param s Scalar
#' @param v Numeric vector
#' @param w Numeric vector of same length as v
#' @return Numeric vector s * v + w (elementwise, fused single-pass via vDSP_vsmaD)
#' @export
fast_vec_smadd <- function(s, v, w) {
    .Call(`_DefDiff_fast_vec_smadd`, s, v, w)
}

#' Fast scalar-divide-vector via Apple Accelerate vDSP (Tier 2e)
#' @param s Scalar numerator
#' @param v Numeric vector denominator (each element used as divisor)
#' @return Numeric vector where result[i] = s / v[i]
#' @export
fast_scalar_div <- function(s, v) {
    .Call(`_DefDiff_fast_scalar_div`, s, v)
}

#' Fast vector-vector elementwise multiply via Apple Accelerate vDSP (Tier 3)
#' @param v Numeric vector
#' @param w Numeric vector of same length
#' @return Numeric vector with v[i] * w[i] elementwise
#' @export
fast_vec_mul <- function(v, w) {
    .Call(`_DefDiff_fast_vec_mul`, v, w)
}

#' Fast vector-vector elementwise divide via Apple Accelerate vDSP (Tier 4 family-2)
#'
#' Computes the elementwise quotient `numerator / denominator`. Wrapper around
#' `vDSP_vdivD`.
#'
#' *** Argument-order note ***: vDSP_vdivD itself takes (denominator, numerator,
#' out, n) — the dividend is the SECOND vDSP arg, divisor is the FIRST. This
#' wrapper inverts the convention so callers pass `(numerator, denominator)`
#' intuitively. A regression would manifest as wrong-direction division
#' (e.g., `fast_vec_div(c(6, 8, 10), c(2, 4, 5))` returning `c(0.333, 0.5, 0.5)`
#' instead of `c(3, 2, 2)`).
#'
#' @param numerator Numeric vector (the dividend)
#' @param denominator Numeric vector of same length as numerator (the divisor)
#' @return Numeric vector with `numerator[i] / denominator[i]` elementwise
#' @export
fast_vec_div <- function(numerator, denominator) {
    .Call(`_DefDiff_fast_vec_div`, numerator, denominator)
}

#' Initialize the Metal scalar-multiply pipeline (internal)
#'
#' Loads the pre-compiled metallib and builds the compute pipeline. Returns
#' FALSE (never raises) when no Metal device / library / kernel is available,
#' so the R-side guard can fall back to the CPU path. Idempotent: a second
#' call with an already-built pipeline returns TRUE immediately.
#'
#' @param metallib_path Filesystem path to scalar_mul.metallib.
#' @return TRUE if the pipeline is ready, FALSE otherwise.
#' @export
metal_scalar_mul_init <- function(metallib_path) {
    .Call(`_DefDiff_metal_scalar_mul_init`, metallib_path)
}

#' Scalar-vector multiply on the Metal GPU (internal)
#'
#' Computes \code{s * v} elementwise via the Metal compute kernel. Inputs are
#' converted to float32 for the GPU and back to double on return, so the
#' result matches the vDSP/base-R double product to within ~1e-6 relative.
#' Requires \code{metal_scalar_mul_init} to have succeeded.
#'
#' @param s Scalar multiplier.
#' @param v Numeric vector.
#' @return Numeric vector equal to s * v (float32 precision).
#' @export
metal_scalar_mul <- function(s, v) {
    .Call(`_DefDiff_metal_scalar_mul`, s, v)
}

